/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'mekanik';
  static const String PLUGIN_VERSION = '1.4.8+1';
  static const String BG = 'assets/bg.png';
  static const String BGABSEN = 'assets/bgabsen.png';
  static const String LOGO_TECH = 'assets/logo_tech.png';
  static const String SOUNDS = 'assets/sounds/sounds.mp3';
  static const String SOUNDS_BOOKING = 'assets/sounds/sounds_booking.mp3';
}
